V11 DDI
Open-Systems-Pharmacology/Probenecid-Furosemide-DDI pull request #2
Opened 2024-12-18 09:52 UTC by mgsc1020

.json file with updated model compounds V11 and qualification plan for OAT DDI

2024-12-18 09:54 UTC, mgsc1020 commented
please review @PavelBal

2025-01-27 11:58 UTC, PavelBal commented on README.md
>  Within this repository, we share a PK-Sim project file containing simulations of all published clinical studies used to evaluate the predictive performance of our models regarding the [Probenecid](ht
Please change "share PK-Sim project" to "Share PK-Sim snapshot" (or how is this formulated in other DDI repos...)

2025-01-27 13:15 UTC, PavelBal commented
Move the DDI ratio data into https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library

2025-01-27 15:30 UTC, PavelBal commented
Please limit x axis to not show too much beyond observed data, e.g. here:

![image](https://github.com/user-attachments/assets/46772f7c-a938-4244-8e13-f5a01f3db4ad)

2025-01-27 15:32 UTC, PavelBal requested changes

2025-03-24 16:21 UTC, PavelBal commented
- [ ] @mgsc1020 To remove local copies of xlsx and csv
- [ ] @mgsc1020 To change the path to DDI.csv to the gibhub version (line 48 to `https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/refs/heads/master/DDI.csv`)
- [ ] @Yuri05 to create a release of https://github.com/Open-Systems-Pharmacology/Database-for-observed-data/releases
- [ ] @mgsc1020 to change the path to DDI.csv to the released version
- [ ] @Yuri05 to create a release of https://github.com/Open-Systems-Pharmacology/Probenecid-Model
- [ ] @Yuri to merge https://github.com/Open-Systems-Pharmacology/Furosemide-Model
- [ ] @Yuri05 to create a release of https://github.com/Open-Systems-Pharmacology/Furosemide-Model
- [ ] @mgsc1020 to replace project paths (lines 6 and 10) to the releases

2025-03-24 16:23 UTC, PavelBal approved these changes

2025-03-24 16:23 UTC, PavelBal commented on Qualification/input/Content/Qualification_DDI_objective.md
> +The respective *qualification plan* to produce this *qualification report* is transparently provided open-source (https://github.com/Open-Systems-Pharmacology/Cimetidine-Metformin-DDI/releases). The
Wrong hyperlink.

2025-03-24 16:24 UTC, PavelBal commented
Can be merged after the actions listed above are done.

2025-04-07 16:39 UTC, Yuri05 commented on Qualification/input/Content/Probenecid-Furosemide-DDI.md
> +|  17004 | OAT   | Probenecid / Furosemide | Probenecid: **1000** mg PO, tablet, SD (D1) Furosemide: **40** mg PO, solution, SD (D1)|   1 h dose gap       | [Shen 2009](#references)        |
@mgsc1020 Seems to be a valid suggestion by AI :)
If so, please click on "Commit suggestion" button above

2025-04-08 07:51 UTC, Yuri05 commented on Qualification/input/Content/References.md
> +
Valid suggestion as well. Please change the file encoding to UTF-8 (without BOM)

2025-06-27 09:00 UTC, PavelBal commented on Qualification/input/qualification_plan.json
> +            "Path": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/refs/heads/master/DDI.csv",
@mgsc1020 Update here to

"https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/v1.5/DDI.csv"

2025-06-27 09:28 UTC, Yuri05 commented on Qualification/input/qualification_plan.json
> +            "Path": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/refs/heads/master/DDI.csv",
v1.7 (=latest) ?

2025-06-27 09:29 UTC, PavelBal commented on Qualification/input/qualification_plan.json
> +            "Path": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Database-for-observed-data/refs/heads/master/DDI.csv",
Ups yes.

2025-07-02 11:56 UTC, PavelBal approved these changes

2025-07-02 11:56 UTC, PavelBal commented on Qualification/input/qualification_plan.json
> +            "Path": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Probenecid-Model/refs/heads/main/Probenecid-Model.json"
Use the releases, e.g. like here https://github.com/Open-Systems-Pharmacology/Qualification-DDI-CYP2C19/blob/e9c1b1dbb0bbd4a636755bd71cc7d98e45b4eaa1/Qualification/Input/qualification_plan.json#L18

2025-07-08 12:04 UTC, PavelBal commented
lgtm, @Yuri05 I think we can merge!

2025-07-08 12:04 UTC, PavelBal commented
And create a release.

2025-07-08 17:05 UTC, merged

2025-07-08 17:09 UTC, Yuri05 commented
(Pre-)Release created